import type { Product, Category, Testimonial } from '@/lib/types';
import { Gamepad2, Laptop, User, Ticket, Sticker, CircleDollarSign } from 'lucide-react';

export const categories: Category[] = [
  { name: 'Игровые ключи', icon: Gamepad2, slug: 'game-keys' },
  { name: 'Программы', icon: Laptop, slug: 'software' },
  { name: 'Аккаунты', icon: User, slug: 'accounts' },
  { name: 'Подарки', icon: Ticket, slug: 'game-gifts' },
  { name: 'Стикеры', icon: Sticker, slug: 'sticker-packs' },
  { name: 'Валюта', icon: CircleDollarSign, slug: 'in-game-currency' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Cyberpunk 2077',
    description: 'Приключенческая ролевая игра с открытым миром, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся выше всего.',
    price: 1599,
    originalPrice: 2999,
    image: 'https://picsum.photos/600/400?random=1',
    dataAiHint: 'futuristic city',
    category: 'Игровые ключи',
    platform: 'PC',
    rating: 4.5,
    reviews: 120,
    tags: ['RPG', 'Открытый мир', 'Киберпанк'],
  },
  {
    id: '2',
    name: 'Pro Video Editor X',
    description: 'Профессиональное программное обеспечение для редактирования видео с расширенными функциями и интуитивно понятным интерфейсом.',
    price: 12999,
    image: 'https://picsum.photos/600/400?random=2',
    dataAiHint: 'video editing',
    category: 'Программы',
    platform: 'Windows/Mac',
    rating: 4.8,
    reviews: 250,
    tags: ['Видео', 'Редактирование', 'Профессиональное'],
  },
  {
    id: '3',
    name: 'The Witcher 3: Wild Hunt',
    description: 'Сюжетная ролевая игра нового поколения с открытым миром, действие которой происходит в потрясающе красивой фэнтезийной вселенной.',
    price: 999,
    image: 'https://picsum.photos/600/400?random=3',
    dataAiHint: 'fantasy landscape',
    category: 'Игровые ключи',
    platform: 'PS5',
    rating: 4.9,
    reviews: 500,
    tags: ['RPG', 'Открытый мир', 'Фэнтези'],
  },
  {
    id: '4',
    name: 'Premium-аккаунт стриминга (1 год)',
    description: 'Годовая подписка на премиальный стриминговый сервис с неограниченным количеством фильмов и сериалов.',
    price: 6999,
    originalPrice: 8399,
    image: 'https://picsum.photos/600/400?random=4',
    dataAiHint: 'movie popcorn',
    category: 'Аккаунты',
    platform: 'Разное',
    rating: 4.7,
    reviews: 85,
    tags: ['Стриминг', 'Подписка', 'Развлечения'],
  },
  {
    id: '5',
    name: 'Набор стикеров "Gamer Fuel"',
    description: 'Набор из 50 высококачественных водонепроницаемых виниловых наклеек для геймеров.',
    price: 499,
    image: 'https://picsum.photos/600/400?random=5',
    dataAiHint: 'cool stickers',
    category: 'Стикеры',
    platform: 'N/A',
    rating: 4.6,
    reviews: 45,
    tags: ['Наклейки', 'Гейминг', 'Аксессуары'],
  },
  {
    id: '6',
    name: '10,000 V-Bucks',
    description: 'Внутриигровая валюта для популярной королевской битвы. Используйте ее для покупки новых предметов кастомизации.',
    price: 5999,
    image: 'https://picsum.photos/600/400?random=6',
    dataAiHint: 'video game',
    category: 'Валюта',
    platform: 'Разное',
    rating: 4.9,
    reviews: 1500,
    tags: ['Валюта', 'Гейминг', 'Fortnite'],
  },
  {
    id: '7',
    name: 'Elden Ring',
    description: 'НОВЫЙ ФЭНТЕЗИЙНЫЙ ЭКШЕН-RPG. Восстань, Погасший, и будь ведом благодатью, чтобы овладеть силой Кольца Элден и стать Лордом Элдена в Междуземье.',
    price: 3999,
    image: 'https://picsum.photos/600/400?random=7',
    dataAiHint: 'dark fantasy',
    category: 'Игровые ключи',
    platform: 'PC',
    rating: 5.0,
    reviews: 2300,
    tags: ['RPG', 'Souls-like', 'Открытый мир'],
  },
  {
    id: '8',
    name: 'Ultimate Graphics Suite',
    description: 'Полный набор инструментов для графического дизайна как для профессионалов, так и для начинающих.',
    price: 29999,
    image: 'https://picsum.photos/600/400?random=8',
    dataAiHint: 'graphic design',
    category: 'Программы',
    platform: 'Windows/Mac',
    rating: 4.7,
    reviews: 310,
    tags: ['Дизайн', 'Креатив', 'Профессиональное'],
  },
];

export const testimonials: Testimonial[] = [
  {
    name: 'Алекс Джонсон',
    role: 'Про-геймер',
    avatar: 'https://picsum.photos/100/100?random=9',
    dataAiHint: 'gamer portrait',
    quote: 'Virtual Vault — мой основной магазин для всех игровых нужд. Мгновенная доставка — это спасение, а их цены — лучшие. Настоятельно рекомендую!',
  },
  {
    name: 'Саманта Би',
    role: 'Графический дизайнер',
    avatar: 'https://picsum.photos/100/100?random=10',
    dataAiHint: 'designer portrait',
    quote: 'Я купила здесь свое программное обеспечение для дизайна, и процесс прошел гладко. Служба поддержки была невероятно полезна, когда у меня возник вопрос по установке.',
  },
  {
    name: 'Майк Т.',
    role: 'Стример',
    avatar: 'https://picsum.photos/100/100?random=11',
    dataAiHint: 'streamer portrait',
    quote: 'Наконец-то появился цифровой рынок, которому я могу доверять. Разнообразие продуктов поражает: от старых игровых ключей до последних подписок на программное обеспечение.',
  },
];
